### ISSUE TITLE
Change color from (fluidd) dashboard

### ISSUE THREAD

**Issue by thijstriemstra** [julianschill/klipper-led_effect#134]
Thanks for this great piece of software!

On my fluidd dashboard there is an option to change the RGB strip color (highlighted in yellow in picture):

![Capture](https://user-images.githubusercontent.com/305679/220915320-f5482498-32a4-4047-8982-a4b5a7a12598.JPG)

Before I could change the color but with klipper-led_effect this isn't possible or seems to not properly work. Is this a planned feature, impossible, or should I file a ticket in the fluidd repository instead?

Config:

```yaml
[neopixel board_rgb]
pin: PB0
chain_count: 8
initial_RED: 0
initial_GREEN: 0
initial_BLUE: 0
color_order: GRB

[led_effect panel_idle]
autostart:              true
frame_rate:             24
leds:
    neopixel:board_rgb
layers:
    breathing  10 1 top (.5,.5,1)
```
